name: Generate a build and push to another branch (DISABLED)

# Disabled to prevent conflicts with Vercel deployment
# Remove this comment and the word DISABLED to re-enable

on:
  # push:
  #   branches:
  #     - main # The branch name your are commit the new changes
  workflow_dispatch: # Only run manually

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    permissions:
      contents: write
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: |
          echo 'const withBundleAnalyzer = require("./scripts/analyze-bundle"); const nextConfig = withBundleAnalyzer({ output: "export", distDir: "out", images: { unoptimized: true }, eslint: { ignoreDuringBuilds: true }, reactStrictMode: true, compress: true, poweredByHeader: false, generateEtags: true, experimental: { optimizeCss: true, optimizePackageImports: ["lucide-react"], scrollRestoration: true }, webpack: (config, { isServer }) => { config.module.rules.push({ test: /\.svg$/i, issuer: /\.[jt]sx?$/, use: [{ loader: "@svgr/webpack", options: { svgoConfig: { plugins: [{ name: "preset-default", params: { overrides: { removeViewBox: false, cleanupIDs: false } } }] } } }] }); return config; } }); module.exports = nextConfig;' > next.config.js
          npm run build

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages # The branch name where you want to push the assets
          FOLDER: out # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
